let mapleader=","

set nocompatible
filetype plugin on
"set packpath^=~/.vim
"packadd minpac
"call minpac#init()
"call minpac#add('k-takata/minpac', {'type': 'opt'})
"call minpac#add('tpope/vim-commentary')

" ********** Indentation **********
set tabstop=4          " Tab character is 4 spaces wide
set shiftwidth=4       " Indentation width for << and >>
set smartindent        " Automatically indent new lines
set autoindent         " Copy indent from current line
set wrap               " Enable line wrapping
set linebreak          " Wrap without cutting words
set expandtab          " Convert tabs to spaces

" ********** Essentials **********

syntax on              " Enable syntax highlighting
set number             " Show line numbers
set relativenumber     " Show relative line numbers
set clipboard=unnamed  " Link system clipboard to unnamed register
set ruler              " Show cursor position
set cursorline         " Highlight current line
set ignorecase         " Case-insensitive search...
set smartcase          " ...unless uppercase is used
set incsearch          " Show matches as you type
set hlsearch           " Highlight all matches
set wildmenu           " Enhanced command-line completion
set title              " Show filename in window title
set titlestring=%F     " Show full path of the file

" ********** Mappings **********

nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>
